#!/usr/bin/env python3
"""Refresh the compatibility table block in README.md from build artifacts.

Reads ``logs/status.json`` files anywhere under ``--artifacts-dir`` (typically
the directory produced by ``actions/download-artifact`` after a matrix run of
``build-tt-metal.yaml``) and rewrites the markdown block enclosed by

    <!-- COMPAT_TABLE_START -->
    ...
    <!-- COMPAT_TABLE_END -->

The script is intentionally dependency-free (stdlib only) so it can run on any
runner image without an extra ``pip install``.

Usage::

    python3 scripts/update_compat_table.py --artifacts-dir _artifacts

Optional flags:
    --readme PATH        path to README.md (default: ./README.md)
    --history-dir PATH   persist per-run JSON snapshots under this directory
    --check              do not write; exit 1 if the README would change
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

# Display order and human-readable names.  Rows for OSes we have not yet
# wired into CI still appear, but as ``⏳``.  Keeping them here means the
# table layout is stable across runs that build different subsets.
ROW_ORDER: list[tuple[str, str]] = [
    ("linuxmint-22.3", "Linux Mint 22.3"),
    ("linuxmint-22.2", "Linux Mint 22.2"),
    ("linuxmint-22.1", "Linux Mint 22.1"),
    ("linuxmint-21.3", "Linux Mint 21.3"),
    ("ubuntu-26.04", "Ubuntu 26.04"),
    ("debian-13", "Debian 13"),
    ("debian-12", "Debian 12"),
    ("rocky-10", "Rocky Linux 10"),
    ("rocky-9", "Rocky Linux 9"),
]

STATUS_EMOJI = {
    "success": "✅",
    "failure": "❌",
    "cancelled": "❌",
    "skipped": "⏳",
}
FAILURE_STAGE_LABELS = {
    "patch": "patch",
    "deps": "deps",
    "build": "build",
    "verify": "verify",
    "install": "install",
    "workflow": "workflow",
}

START_MARKER = "<!-- COMPAT_TABLE_START -->"
END_MARKER = "<!-- COMPAT_TABLE_END -->"
INSTALL_START_MARKER = "<!-- INSTALL_TABLE_START -->"
INSTALL_END_MARKER = "<!-- INSTALL_TABLE_END -->"
HEADER_NOTE = (
    "*The table below is auto-generated by CI. "
    "Last update timestamp and tested commit appear above the table.*"
)
INSTALL_HEADER_NOTE = (
    "*Auto-generated. tt-installer phase is opt-in per OS; "
    "rows marked `—` are not yet wired into CI.*"
)
HISTORY_SCHEMA_VERSION = 1


def collect(artifacts_dir: Path) -> dict[str, dict]:
    """Return a mapping of ``target_os`` → status.json dict.

    The most recently modified status.json wins per OS, so feeding multiple
    overlapping artifact sets is safe.
    """
    by_os: dict[str, dict] = {}
    candidates = sorted(
        artifacts_dir.rglob("status.json"),
        key=lambda p: p.stat().st_mtime,
    )
    for status_path in candidates:
        try:
            data = json.loads(status_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"warn: cannot parse {status_path}: {exc}", file=sys.stderr)
            continue
        if not isinstance(data, dict):
            print(f"warn: {status_path} is not a JSON object", file=sys.stderr)
            continue
        os_id = data.get("target_os")
        if not os_id:
            print(f"warn: {status_path} has no target_os field", file=sys.stderr)
            continue
        by_os[os_id] = data
    return by_os


def ordered_results(by_os: dict[str, dict]) -> list[tuple[str, dict]]:
    """Return results in table order, with unknown OSes appended alphabetically."""
    ordered: list[tuple[str, dict]] = []
    seen: set[str] = set()
    for os_id, _ in ROW_ORDER:
        if os_id in by_os:
            ordered.append((os_id, by_os[os_id]))
            seen.add(os_id)
    for os_id in sorted(set(by_os) - seen):
        ordered.append((os_id, by_os[os_id]))
    return ordered


def first_value(results: list[tuple[str, dict]], key: str) -> str:
    """Return the first non-empty string value for ``key`` in ordered results."""
    for _, data in results:
        value = data.get(key)
        if value:
            return str(value)
    return ""


def safe_path_component(value: str) -> str:
    """Sanitize a JSON-derived identifier before using it in a path."""
    safe = "".join(ch if ch.isalnum() or ch in "._-" else "-" for ch in value)
    return safe.strip(".-") or "unknown"


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def history_summary(data: dict) -> dict:
    """Return the compact per-OS summary stored in history/latest and index."""
    return {
        "target_os": data.get("target_os", ""),
        "distro": data.get("distro", ""),
        "version": data.get("version", ""),
        "status": data.get("status", ""),
        "vanilla_status": data.get("vanilla_status", ""),
        "vanilla_failure_stage": data.get("vanilla_failure_stage", ""),
        "failure_stage": data.get("failure_stage", ""),
        "patch_count": data.get("patch_count", 0),
        "install_status_vanilla": (
            data.get("install_status_vanilla")
            or data.get("install_status")
            or "na"
        ),
        "install_status_patched": data.get("install_status_patched", "na"),
        "install_patch_count": data.get("install_patch_count", 0),
    }


def build_history_entry(
    results: list[tuple[str, dict]],
    recorded_at: str,
    run_id: str,
    run_dir: str,
) -> dict:
    """Build the compact run-level entry used by latest.json and index.json."""
    return {
        "schema_version": HISTORY_SCHEMA_VERSION,
        "recorded_at": recorded_at,
        "run_id": run_id,
        "run_dir": run_dir,
        "run_url": first_value(results, "run_url"),
        "tt_metal_repo": first_value(results, "tt_metal_repo"),
        "tt_metal_ref": first_value(results, "tt_metal_ref"),
        "tt_metal_sha": first_value(results, "tt_metal_sha"),
        "target_count": len(results),
        "targets": [history_summary(data) for _, data in results],
    }


def write_history(by_os: dict[str, dict], history_dir: Path) -> None:
    """Persist raw per-run status JSON plus compact latest/index files."""
    results = ordered_results(by_os)
    if not results:
        print("history unchanged: no OS results found")
        return

    recorded_at = (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )
    run_ids = sorted(
        {str(data.get("run_id")) for _, data in results if data.get("run_id")}
    )
    run_id = run_ids[0] if len(run_ids) == 1 else f"mixed-{recorded_at}"
    run_id_safe = safe_path_component(run_id)
    run_dir = f"runs/{run_id_safe}"
    run_path = history_dir / run_dir

    for os_id, data in results:
        snapshot = dict(data)
        snapshot["history_schema_version"] = HISTORY_SCHEMA_VERSION
        snapshot["history_recorded_at"] = recorded_at
        write_json(run_path / f"{safe_path_component(os_id)}.json", snapshot)

    entry = build_history_entry(results, recorded_at, run_id, run_dir)
    write_json(history_dir / "latest.json", entry)

    index_path = history_dir / "index.json"
    if index_path.exists():
        try:
            index = json.loads(index_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise SystemExit(f"cannot parse {index_path}: {exc}") from exc
        if not isinstance(index, dict):
            raise SystemExit(f"{index_path} is not a JSON object")
        runs = index.get("runs", [])
        if not isinstance(runs, list):
            raise SystemExit(f"{index_path}: runs must be a list")
    else:
        runs = []

    runs = [
        run
        for run in runs
        if not isinstance(run, dict) or str(run.get("run_id")) != run_id
    ]
    runs.insert(0, entry)
    write_json(
        index_path,
        {
            "schema_version": HISTORY_SCHEMA_VERSION,
            "updated_at": recorded_at,
            "runs": runs,
        },
    )
    print(f"history updated: {run_dir} ({len(results)} OS result(s))")


def status_cell(status: str, stage: str = "") -> str:
    """Return an emoji status cell, adding a short stage hint on failures."""
    normalized = (status or "").lower()
    emoji = STATUS_EMOJI.get(normalized, "⏳")
    stage_label = FAILURE_STAGE_LABELS.get((stage or "").lower(), "")
    if emoji == "❌" and stage_label:
        return f"{emoji}({stage_label})"
    return emoji


def first_failed_stage(data: dict) -> str:
    """Infer the first failed build pipeline stage from a status.json object."""
    explicit = str(data.get("failure_stage") or "").lower()
    if explicit and explicit != "na":
        return explicit
    for key, stage in (
        ("patch_status_patched", "patch"),
        ("deps_status_patched", "deps"),
        ("build_status_patched", "build"),
        ("artifact_status", "verify"),
    ):
        if str(data.get(key) or "").lower() == "failure":
            return stage
    if str(data.get("status") or "").lower() in {"failure", "cancelled"}:
        return "workflow"
    return ""


def render(by_os: dict[str, dict]) -> str:
    sha = ""
    ref = ""
    for data in by_os.values():
        val_sha = data.get("tt_metal_sha")
        if not sha and val_sha:
            sha = str(val_sha)
        val_ref = data.get("tt_metal_ref")
        if not ref and val_ref:
            ref = str(val_ref)
        if sha and ref:
            break
    sha_short = sha[:7] if sha else "<sha>"
    ref = ref or "main"
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append(HEADER_NOTE)
    lines.append("")
    lines.append(f"**Last updated:** {ts}")
    lines.append(f"**Tested tt-metal:** `{ref}@{sha_short}`")
    lines.append("")
    lines.append("| Distribution | Vanilla | With patches | Logs |")
    lines.append("|---|:-:|:-:|---|")
    known_oses = {os_id for os_id, _ in ROW_ORDER}
    for os_id in by_os:
        if os_id not in known_oses:
            print(
                f"warn: OS '{os_id}' found in artifacts but missing from ROW_ORDER",
                file=sys.stderr,
            )
    for os_id, name in ROW_ORDER:
        data = by_os.get(os_id)
        if data:
            patched_status = (data.get("status") or "").lower()
            patched_emoji = status_cell(patched_status, first_failed_stage(data))
            run_url = data.get("run_url", "")
            log_cell = f"[run]({run_url})" if run_url else "—"

            try:
                patch_count = int(data.get("patch_count") or 0)
            except (TypeError, ValueError):
                patch_count = 0
            vanilla_status = (data.get("vanilla_status") or "").lower()

            if patch_count == 0:
                # No patches needed for this distro: vanilla and patched
                # are by definition identical.  Showing the same emoji in
                # both columns with a "(no patches)" note keeps the
                # contrast visible without misrepresenting the data.
                vanilla_cell = patched_emoji
                patched_cell = f"{patched_emoji} (no patches)"
            else:
                # Patches exist.  vanilla_status comes from the pre-flight
                # pass that runs install_dependencies.sh without applying
                # them; older artifacts may not have this field, in which
                # case we leave the cell as ⏳ rather than guess.
                vanilla_cell = status_cell(
                    vanilla_status,
                    str(data.get("vanilla_failure_stage") or ""),
                )
                patches_dir = f"patches/{(data.get('distro') or '').lower()}"
                noun = "patch" if patch_count == 1 else "patches"
                patched_cell = (
                    f"{patched_emoji} ([{patch_count} {noun}]({patches_dir}/))"
                )
        else:
            vanilla_cell = "⏳"
            patched_cell = "⏳"
            log_cell = "—"
        lines.append(f"| {name} | {vanilla_cell} | {patched_cell} | {log_cell} |")
    return "\n".join(lines)


def render_install(by_os: dict[str, dict]) -> str:
    """Render the tt-installer verification table.

    Schema mirrors the build (deps/build) table: a Vanilla column shows
    the result of the released ``install.sh`` and a "With patches"
    column shows the result of running install.sh after applying the
    patches in ``patches/<distro>/installer/``. OSes that need no
    installer patches (``install_patch_count == 0``) synthesise the
    patched cell from the vanilla result and tag it ``(no patches)`` so
    the column is never empty.
    """
    lines: list[str] = []
    lines.append(INSTALL_HEADER_NOTE)
    lines.append("")
    lines.append("| Distribution | Vanilla | With patches | Logs |")
    lines.append("|---|:-:|:-:|---|")
    for os_id, name in ROW_ORDER:
        data = by_os.get(os_id) or {}
        # Prefer the new per-leg fields; fall back to the legacy
        # install_* keys so old artifacts (one cycle of overlap) still
        # render.
        vanilla_status = (
            data.get("install_status_vanilla")
            or data.get("install_status")
            or "na"
        ).lower()
        patched_status = (data.get("install_status_patched") or "na").lower()
        try:
            install_patch_count = int(data.get("install_patch_count") or 0)
        except (TypeError, ValueError):
            install_patch_count = 0

        if vanilla_status == "na":
            lines.append(f"| {name} | — | — | — |")
            continue

        vanilla_emoji = status_cell(vanilla_status, "install")
        installer_version = data.get("installer_version") or ""
        version_suffix = f" (`{installer_version}`)" if installer_version else ""
        vanilla_cell = f"{vanilla_emoji}{version_suffix}"

        if install_patch_count == 0:
            # No installer patches for this distro -> the patched
            # column is by definition the vanilla result.
            patched_cell = f"{vanilla_emoji} (no patches)"
        else:
            patched_emoji = status_cell(patched_status, "install")
            patches_dir = (
                data.get("install_patch_dir")
                or f"patches/{(data.get('distro') or os_id.split('-')[0]).lower()}/installer"
            )
            noun = "patch" if install_patch_count == 1 else "patches"
            patched_cell = (
                f"{patched_emoji} ([{install_patch_count} {noun}]({patches_dir}/))"
            )

        run_url = data.get("run_url", "")
        log_cell = f"[run]({run_url})" if run_url else "—"
        lines.append(f"| {name} | {vanilla_cell} | {patched_cell} | {log_cell} |")
    return "\n".join(lines)


def replace_block(readme_text: str, body: str,
                  start: str = START_MARKER,
                  end: str = END_MARKER) -> str:
    s = readme_text.find(start)
    e = readme_text.find(end)
    if s == -1 or e == -1:
        raise SystemExit(f"markers not found in README: {start}/{end}")
    if e < s:
        raise SystemExit(f"markers are out of order in README: {start}/{end}")
    head = readme_text[: s + len(start)]
    tail = readme_text[e:]
    return f"{head}\n{body}\n{tail}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--artifacts-dir", required=True, type=Path)
    ap.add_argument("--readme", default=Path("README.md"), type=Path)
    ap.add_argument("--history-dir", type=Path,
                    help="write per-run status snapshots and history index")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the README would change; do not write")
    ap.add_argument("--require-os", nargs="+", default=[],
                    help="fail if any of these target_os values is missing "
                         "from the collected status.json files")
    args = ap.parse_args()

    if not args.artifacts_dir.is_dir():
        print(
            f"error: {args.artifacts_dir} is not a directory",
            file=sys.stderr,
        )
        return 1

    by_os = collect(args.artifacts_dir)

    missing = [os_id for os_id in args.require_os if os_id not in by_os]
    if missing:
        print(
            "error: required target_os values are missing: "
            + ", ".join(missing),
            file=sys.stderr,
        )
        return 2

    body = render(by_os)
    install_body = render_install(by_os)
    old = args.readme.read_text(encoding="utf-8")
    new = replace_block(old, body, START_MARKER, END_MARKER)
    # The install-phase table is optional: only update it if the
    # corresponding markers are present, so the script remains
    # backward-compatible with branches/forks that do not have it
    # yet.
    if INSTALL_START_MARKER in new and INSTALL_END_MARKER in new:
        new = replace_block(new, install_body,
                            INSTALL_START_MARKER, INSTALL_END_MARKER)

    if args.check:
        if old != new:
            print("README compat table is out of date", file=sys.stderr)
            return 1
        return 0

    if old != new:
        args.readme.write_text(new, encoding="utf-8")
    if args.history_dir:
        write_history(by_os, args.history_dir)
    print(f"processed {len(by_os)} OS result(s); README {'updated' if old != new else 'unchanged'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
