#!/usr/bin/env python3
"""Refresh the compatibility table block in README.md from build artifacts.

Reads ``logs/status.json`` files anywhere under ``--artifacts-dir`` (typically
the directory produced by ``actions/download-artifact`` after a matrix run of
``build-tt-metal.yaml``) and rewrites the markdown block enclosed by

    <!-- COMPAT_TABLE_START -->
    ...
    <!-- COMPAT_TABLE_END -->

The script is intentionally dependency-free (stdlib only) so it can run on any
runner image without an extra ``pip install``.

Usage::

    python3 scripts/update_compat_table.py --artifacts-dir _artifacts

Optional flags:
    --readme PATH        path to README.md (default: ./README.md)
    --check              do not write; exit 1 if the README would change
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

# Display order and human-readable names.  Rows for OSes we have not yet
# wired into CI still appear, but as ``⏳``.  Keeping them here means the
# table layout is stable across runs that build different subsets.
ROW_ORDER: list[tuple[str, str]] = [
    ("linuxmint-22.3", "Linux Mint 22.3"),
    ("linuxmint-22.2", "Linux Mint 22.2"),
    ("linuxmint-22.1", "Linux Mint 22.1"),
    ("linuxmint-21.3", "Linux Mint 21.3"),
    ("ubuntu-26.04", "Ubuntu 26.04"),
    ("debian-13", "Debian 13"),
    ("debian-12", "Debian 12"),
    ("rocky-10", "Rocky Linux 10"),
    ("rocky-9", "Rocky Linux 9"),
]

STATUS_EMOJI = {
    "success": "✅",
    "failure": "❌",
    "cancelled": "❌",
    "skipped": "⏳",
}

START_MARKER = "<!-- COMPAT_TABLE_START -->"
END_MARKER = "<!-- COMPAT_TABLE_END -->"
HEADER_NOTE = (
    "*The table below is auto-generated by CI. "
    "Last update timestamp and tested commit appear above the table.*"
)


def collect(artifacts_dir: Path) -> dict[str, dict]:
    """Return a mapping of ``target_os`` → status.json dict.

    The most recently modified status.json wins per OS, so feeding multiple
    overlapping artifact sets is safe.
    """
    by_os: dict[str, dict] = {}
    candidates = sorted(
        artifacts_dir.rglob("status.json"),
        key=lambda p: p.stat().st_mtime,
    )
    for status_path in candidates:
        try:
            data = json.loads(status_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"warn: cannot parse {status_path}: {exc}", file=sys.stderr)
            continue
        if not isinstance(data, dict):
            print(f"warn: {status_path} is not a JSON object", file=sys.stderr)
            continue
        os_id = data.get("target_os")
        if not os_id:
            print(f"warn: {status_path} has no target_os field", file=sys.stderr)
            continue
        by_os[os_id] = data
    return by_os


def render(by_os: dict[str, dict]) -> str:
    sha = ""
    ref = ""
    for data in by_os.values():
        val_sha = data.get("tt_metal_sha")
        if not sha and val_sha:
            sha = str(val_sha)
        val_ref = data.get("tt_metal_ref")
        if not ref and val_ref:
            ref = str(val_ref)
        if sha and ref:
            break
    sha_short = sha[:7] if sha else "<sha>"
    ref = ref or "main"
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append(HEADER_NOTE)
    lines.append("")
    lines.append(f"**Last updated:** {ts}")
    lines.append(f"**Tested tt-metal:** `{ref}@{sha_short}`")
    lines.append("")
    lines.append("| Distribution | Vanilla | With patches | Logs |")
    lines.append("|---|:-:|:-:|---|")
    known_oses = {os_id for os_id, _ in ROW_ORDER}
    for os_id in by_os:
        if os_id not in known_oses:
            print(
                f"warn: OS '{os_id}' found in artifacts but missing from ROW_ORDER",
                file=sys.stderr,
            )
    for os_id, name in ROW_ORDER:
        data = by_os.get(os_id)
        if data:
            patched_status = (data.get("status") or "").lower()
            patched_emoji = STATUS_EMOJI.get(patched_status, "⏳")
            run_url = data.get("run_url", "")
            log_cell = f"[run]({run_url})" if run_url else "—"

            try:
                patch_count = int(data.get("patch_count") or 0)
            except (TypeError, ValueError):
                patch_count = 0
            vanilla_status = (data.get("vanilla_status") or "").lower()

            if patch_count == 0:
                # No patches needed for this distro: vanilla and patched
                # are by definition identical.  Showing the same emoji in
                # both columns with a "(no patches)" note keeps the
                # contrast visible without misrepresenting the data.
                vanilla_cell = patched_emoji
                patched_cell = f"{patched_emoji} (no patches)"
            else:
                # Patches exist.  vanilla_status comes from the pre-flight
                # pass that runs install_dependencies.sh without applying
                # them; older artifacts may not have this field, in which
                # case we leave the cell as ⏳ rather than guess.
                vanilla_cell = STATUS_EMOJI.get(vanilla_status, "⏳")
                patches_dir = f"patches/{(data.get('distro') or '').lower()}"
                noun = "patch" if patch_count == 1 else "patches"
                patched_cell = (
                    f"{patched_emoji} ([{patch_count} {noun}]({patches_dir}/))"
                )
        else:
            vanilla_cell = "⏳"
            patched_cell = "⏳"
            log_cell = "—"
        lines.append(f"| {name} | {vanilla_cell} | {patched_cell} | {log_cell} |")
    return "\n".join(lines)


def replace_block(readme_text: str, body: str) -> str:
    s = readme_text.find(START_MARKER)
    e = readme_text.find(END_MARKER)
    if s == -1 or e == -1:
        raise SystemExit("compat table markers not found in README")
    if e < s:
        raise SystemExit("compat table markers are out of order in README")
    head = readme_text[: s + len(START_MARKER)]
    tail = readme_text[e:]
    return f"{head}\n{body}\n{tail}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--artifacts-dir", required=True, type=Path)
    ap.add_argument("--readme", default=Path("README.md"), type=Path)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the README would change; do not write")
    ap.add_argument("--require-os", nargs="+", default=[],
                    help="fail if any of these target_os values is missing "
                         "from the collected status.json files")
    args = ap.parse_args()

    if not args.artifacts_dir.is_dir():
        print(
            f"error: {args.artifacts_dir} is not a directory",
            file=sys.stderr,
        )
        return 1

    by_os = collect(args.artifacts_dir)

    missing = [os_id for os_id in args.require_os if os_id not in by_os]
    if missing:
        print(
            "error: required target_os values are missing: "
            + ", ".join(missing),
            file=sys.stderr,
        )
        return 2

    body = render(by_os)
    old = args.readme.read_text(encoding="utf-8")
    new = replace_block(old, body)

    if args.check:
        if old != new:
            print("README compat table is out of date", file=sys.stderr)
            return 1
        return 0

    if old != new:
        args.readme.write_text(new, encoding="utf-8")
    print(f"processed {len(by_os)} OS result(s); README {'updated' if old != new else 'unchanged'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
