#!/usr/bin/env python3
"""Refresh the compatibility table block in README.md from build artifacts.

Reads ``logs/status.json`` files anywhere under ``--artifacts-dir`` (typically
the directory produced by ``actions/download-artifact`` after a matrix run of
``build-tt-metal.yaml``) and rewrites the markdown block enclosed by

    <!-- COMPAT_TABLE_START -->
    ...
    <!-- COMPAT_TABLE_END -->

When ``--history-dir`` is supplied, it also refreshes the optional
``HISTORY_SUMMARY`` block and writes a static SVG trend chart under
``history/``.

The script is intentionally dependency-free (stdlib only) so it can run on any
runner image without an extra ``pip install``.

Usage::

    python3 scripts/update_compat_table.py --artifacts-dir _artifacts

Optional flags:
    --readme PATH        path to README.md (default: ./README.md)
    --history-dir PATH   persist per-run JSON snapshots under this directory
    --check              do not write; exit 1 if the README would change
"""
from __future__ import annotations

import argparse
import html
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

# Display order and human-readable names.  Rows for OSes we have not yet
# wired into CI still appear, but as ``⏳``.  Keeping them here means the
# table layout is stable across runs that build different subsets.
ROW_ORDER: list[tuple[str, str]] = [
    ("linuxmint-22.3", "Linux Mint 22.3"),
    ("linuxmint-22.2", "Linux Mint 22.2"),
    ("linuxmint-22.1", "Linux Mint 22.1"),
    ("linuxmint-21.3", "Linux Mint 21.3"),
    ("ubuntu-26.04", "Ubuntu 26.04"),
    ("debian-13", "Debian 13"),
    ("debian-12", "Debian 12"),
    ("rocky-10", "Rocky Linux 10"),
    ("rocky-9", "Rocky Linux 9"),
]

STATUS_EMOJI = {
    "success": "✅",
    "failure": "❌",
    "cancelled": "❌",
    "skipped": "⏳",
}
FAILURE_STAGE_LABELS = {
    "patch": "patch",
    "deps": "deps",
    "build": "build",
    "verify": "verify",
    "install": "install",
    "runtime": "runtime",
    "workflow": "workflow",
}

START_MARKER = "<!-- COMPAT_TABLE_START -->"
END_MARKER = "<!-- COMPAT_TABLE_END -->"
INSTALL_START_MARKER = "<!-- INSTALL_TABLE_START -->"
INSTALL_END_MARKER = "<!-- INSTALL_TABLE_END -->"
HISTORY_START_MARKER = "<!-- HISTORY_SUMMARY_START -->"
HISTORY_END_MARKER = "<!-- HISTORY_SUMMARY_END -->"
HEADER_NOTE = (
    "*The table below is auto-generated by CI. "
    "Last update timestamp and tested commit appear above the table.*"
)
INSTALL_HEADER_NOTE = (
    "*Auto-generated. tt-installer phase is opt-in per OS; "
    "rows marked `—` are not yet wired into CI.*"
)
HISTORY_SCHEMA_VERSION = 1
HISTORY_INDEX_LIMIT = 100
HISTORY_RECENT_LIMIT = 5
HISTORY_SVG_LIMIT = 12
HISTORY_SVG_NAME = "compatibility-history.svg"


def collect(artifacts_dir: Path) -> dict[str, dict]:
    """Return a mapping of ``target_os`` → status.json dict.

    The most recently modified status.json wins per OS, so feeding multiple
    overlapping artifact sets is safe.
    """
    by_os: dict[str, dict] = {}
    candidates = sorted(
        artifacts_dir.rglob("status.json"),
        key=lambda p: p.stat().st_mtime,
    )
    for status_path in candidates:
        try:
            data = json.loads(status_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"warn: cannot parse {status_path}: {exc}", file=sys.stderr)
            continue
        if not isinstance(data, dict):
            print(f"warn: {status_path} is not a JSON object", file=sys.stderr)
            continue
        os_id = data.get("target_os")
        if not os_id:
            print(f"warn: {status_path} has no target_os field", file=sys.stderr)
            continue
        by_os[os_id] = data
    return by_os


def ordered_results(by_os: dict[str, dict]) -> list[tuple[str, dict]]:
    """Return results in table order, with unknown OSes appended alphabetically."""
    ordered: list[tuple[str, dict]] = []
    seen: set[str] = set()
    for os_id, _ in ROW_ORDER:
        if os_id in by_os:
            ordered.append((os_id, by_os[os_id]))
            seen.add(os_id)
    for os_id in sorted(set(by_os) - seen):
        ordered.append((os_id, by_os[os_id]))
    return ordered


def first_value(results: list[tuple[str, dict]], key: str) -> str:
    """Return the first non-empty string value for ``key`` in ordered results."""
    for _, data in results:
        value = data.get(key)
        if value:
            return str(value)
    return ""


def safe_path_component(value: str) -> str:
    """Sanitize a JSON-derived identifier before using it in a path."""
    safe = "".join(ch if ch.isalnum() or ch in "._-" else "-" for ch in value)
    return safe.strip(".-") or "unknown"


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def history_summary(data: dict) -> dict:
    """Return the compact per-OS summary stored in history/latest and index."""
    return {
        "target_os": data.get("target_os", ""),
        "distro": data.get("distro", ""),
        "version": data.get("version", ""),
        "status": data.get("status", ""),
        "vanilla_status": data.get("vanilla_status", ""),
        "vanilla_failure_stage": data.get("vanilla_failure_stage", ""),
        "failure_stage": data.get("failure_stage", ""),
        "patch_count": data.get("patch_count", 0),
        "install_status_vanilla": (
            data.get("install_status_vanilla")
            or data.get("install_status")
            or "na"
        ),
        "install_status_patched": data.get("install_status_patched", "na"),
        "install_patch_count": data.get("install_patch_count", 0),
        "runtime_status": data.get("runtime_status", "na"),
        "runtime_failure_stage": data.get("runtime_failure_stage", "na"),
        "runtime_smoke_target": data.get("runtime_smoke_target", ""),
    }


def build_history_entry(
    results: list[tuple[str, dict]],
    recorded_at: str,
    run_id: str,
    run_dir: str,
) -> dict:
    """Build the compact run-level entry used by latest.json and index.json."""
    return {
        "schema_version": HISTORY_SCHEMA_VERSION,
        "recorded_at": recorded_at,
        "run_id": run_id,
        "run_dir": run_dir,
        "run_url": first_value(results, "run_url"),
        "tt_metal_repo": first_value(results, "tt_metal_repo"),
        "tt_metal_ref": first_value(results, "tt_metal_ref"),
        "tt_metal_sha": first_value(results, "tt_metal_sha"),
        "target_count": len(results),
        "targets": [history_summary(data) for _, data in results],
    }


def read_history_index(index_path: Path) -> dict:
    """Read a history index, returning an empty index when it does not exist."""
    if not index_path.exists():
        return {
            "schema_version": HISTORY_SCHEMA_VERSION,
            "updated_at": "",
            "runs": [],
        }
    try:
        index = json.loads(index_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"cannot parse {index_path}: {exc}") from exc
    if not isinstance(index, dict):
        raise SystemExit(f"{index_path} is not a JSON object")
    runs = index.get("runs", [])
    if not isinstance(runs, list):
        raise SystemExit(f"{index_path}: runs must be a list")
    return index


def updated_history_index(by_os: dict[str, dict], history_dir: Path,
                          recorded_at: str) -> tuple[str, dict]:
    """Return the run directory and index payload after adding ``by_os``."""
    results = ordered_results(by_os)
    if not results:
        return "", read_history_index(history_dir / "index.json")

    run_ids = sorted(
        {str(data.get("run_id")) for _, data in results if data.get("run_id")}
    )
    run_id = run_ids[0] if len(run_ids) == 1 else f"mixed-{recorded_at}"
    run_id_safe = safe_path_component(run_id)
    run_dir = f"runs/{run_id_safe}"

    entry = build_history_entry(results, recorded_at, run_id, run_dir)
    index_path = history_dir / "index.json"
    index = read_history_index(index_path)
    runs = index.get("runs", [])
    runs = [
        run
        for run in runs
        if not isinstance(run, dict) or str(run.get("run_id")) != run_id
    ]
    runs.insert(0, entry)
    runs = runs[:HISTORY_INDEX_LIMIT]
    return run_dir, {
        "schema_version": HISTORY_SCHEMA_VERSION,
        "updated_at": recorded_at,
        "runs": runs,
    }


def write_history(by_os: dict[str, dict], history_dir: Path,
                  recorded_at: str,
                  prepared: tuple[str, dict] | None = None) -> dict:
    """Persist raw per-run status JSON plus compact latest/index files."""
    results = ordered_results(by_os)
    if not results:
        print("history unchanged: no OS results found")
        return read_history_index(history_dir / "index.json")

    run_dir, index = prepared or updated_history_index(
        by_os, history_dir, recorded_at
    )
    run_path = history_dir / run_dir

    for os_id, data in results:
        snapshot = dict(data)
        snapshot["history_schema_version"] = HISTORY_SCHEMA_VERSION
        snapshot["history_recorded_at"] = recorded_at
        write_json(run_path / f"{safe_path_component(os_id)}.json", snapshot)

    latest = index["runs"][0]
    write_json(history_dir / "latest.json", latest)
    write_json(history_dir / "index.json", index)
    print(f"history updated: {run_dir} ({len(results)} OS result(s))")
    return index


def compatible_history_runs(index: dict) -> list[dict]:
    """Return history entries this renderer understands."""
    runs = index.get("runs", [])
    if not isinstance(runs, list):
        return []
    compatible: list[dict] = []
    for run in runs:
        if not isinstance(run, dict):
            continue
        schema = run.get("schema_version", HISTORY_SCHEMA_VERSION)
        if schema != HISTORY_SCHEMA_VERSION:
            continue
        compatible.append(run)
    return compatible


def effective_install_status(target: dict) -> str:
    """Return the install result that matches the README's patched column.

    Distro entries with no installer patches use the vanilla installer result.
    Entries with installer patches use the patched leg only when it produced a
    concrete result; otherwise they are unknown and excluded from pass ratios.
    """
    try:
        install_patch_count = int(target.get("install_patch_count") or 0)
    except (TypeError, ValueError):
        install_patch_count = 0
    vanilla = str(
        target.get("install_status_vanilla")
        or target.get("install_status")
        or "na"
    ).lower()
    patched = str(target.get("install_status_patched") or "na").lower()
    if install_patch_count == 0:
        return vanilla
    return patched if patched != "na" else "na"


def count_statuses(statuses: list[str]) -> tuple[int, int, int]:
    """Return (successes, known results, unknown results)."""
    normalized = [status.lower() for status in statuses]
    known = [status for status in normalized if status and status != "na"]
    successes = sum(1 for status in known if status == "success")
    unknown = len(normalized) - len(known)
    return successes, len(known), unknown


def format_ratio(successes: int, known: int, unknown: int) -> str:
    if known == 0:
        return "—" if unknown == 0 else f"— ({unknown} unknown)"
    suffix = f" ({unknown} unknown)" if unknown else ""
    return f"{successes}/{known}{suffix}"


def target_display_name(target: dict) -> str:
    os_id = str(target.get("target_os") or "")
    names = dict(ROW_ORDER)
    return names.get(os_id, os_id or "unknown")


def history_run_metrics(run: dict) -> dict:
    """Compute README/SVG metrics for one history run."""
    targets = run.get("targets", [])
    if not isinstance(targets, list):
        targets = []
    target_dicts = [target for target in targets if isinstance(target, dict)]

    build_statuses = [
        str(target.get("status") or "na").lower()
        for target in target_dicts
    ]
    install_statuses = [
        effective_install_status(target)
        for target in target_dicts
    ]
    build = count_statuses(build_statuses)
    install = count_statuses(install_statuses)
    runtime_statuses = [
        str(target.get("runtime_status") or "na").lower()
        for target in target_dicts
    ]
    runtime = count_statuses(runtime_statuses)

    failures: list[str] = []
    for target, status in zip(target_dicts, build_statuses):
        if status not in {"", "na", "success"}:
            stage = str(target.get("failure_stage") or "").lower()
            suffix = f" ({stage})" if stage and stage != "na" else ""
            failures.append(f"{target_display_name(target)} build{suffix}")
    for target, status in zip(target_dicts, install_statuses):
        if status not in {"", "na", "success"}:
            failures.append(f"{target_display_name(target)} install")
    for target, status in zip(target_dicts, runtime_statuses):
        if status not in {"", "na", "success"}:
            failures.append(f"{target_display_name(target)} runtime")

    return {
        "build_success": build[0],
        "build_known": build[1],
        "build_unknown": build[2],
        "install_success": install[0],
        "install_known": install[1],
        "install_unknown": install[2],
        "runtime_success": runtime[0],
        "runtime_known": runtime[1],
        "runtime_unknown": runtime[2],
        "failures": failures,
    }


def trend_color(successes: int, known: int, unknown: int) -> str:
    if known == 0:
        return "#6e7781"
    if successes == known and unknown == 0:
        return "#2da44e"
    if successes == known:
        return "#bf8700"
    return "#cf222e"


def svg_text(x: int, y: int, text: str, *,
             size: int = 12, weight: str = "400",
             anchor: str = "start", fill: str = "#24292f") -> str:
    return (
        f'<text x="{x}" y="{y}" font-size="{size}" '
        f'font-weight="{weight}" text-anchor="{anchor}" fill="{fill}">'
        f'{html.escape(text)}</text>'
    )


def render_history_svg(index: dict) -> str:
    """Render a deterministic SVG trend chart from recent history entries."""
    runs = sorted(
        compatible_history_runs(index),
        key=lambda run: str(run.get("recorded_at") or ""),
    )[-HISTORY_SVG_LIMIT:]
    cell = 24
    gap = 8
    left = 86
    right = 20
    top = 52
    width = max(520, left + right + max(1, len(runs)) * (cell + gap))
    height = 174
    latest = runs[-1].get("recorded_at", "") if runs else ""

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">',
        '<title id="title">Compatibility history</title>',
        '<desc id="desc">Recent full-matrix patched build, installer, and runtime outcomes.</desc>',
        '<rect width="100%" height="100%" fill="#ffffff" rx="8"/>',
        svg_text(12, 22, "Compatibility history", size=14, weight="600"),
        svg_text(12, 40, f"Latest: {latest[:10] or 'n/a'}", size=11, fill="#57606a"),
        svg_text(12, top + 17, "Build", size=12, weight="600"),
        svg_text(12, top + 49, "Installer", size=12, weight="600"),
        svg_text(12, top + 81, "Runtime", size=12, weight="600"),
    ]

    if not runs:
        lines.append(svg_text(left, top + 30, "No history yet", fill="#57606a"))
    for idx, run in enumerate(runs):
        metrics = history_run_metrics(run)
        x = left + idx * (cell + gap)
        date = str(run.get("recorded_at") or "")[5:10] or "n/a"
        run_id = str(run.get("run_id") or "")
        build_title = (
            f"build {metrics['build_success']}/{metrics['build_known']}"
        )
        install_title = (
            f"installer {metrics['install_success']}/{metrics['install_known']}"
        )
        runtime_title = (
            f"runtime {metrics['runtime_success']}/{metrics['runtime_known']}"
        )
        lines.extend([
            svg_text(x + cell // 2, top - 6, date, size=10, anchor="middle", fill="#57606a"),
            f'<rect x="{x}" y="{top}" width="{cell}" height="{cell}" rx="4" '
            f'fill="{trend_color(metrics["build_success"], metrics["build_known"], metrics["build_unknown"])}">'
            f'<title>{html.escape(run_id + " " + build_title)}</title></rect>',
            f'<rect x="{x}" y="{top + 32}" width="{cell}" height="{cell}" rx="4" '
            f'fill="{trend_color(metrics["install_success"], metrics["install_known"], metrics["install_unknown"])}">'
            f'<title>{html.escape(run_id + " " + install_title)}</title></rect>',
            f'<rect x="{x}" y="{top + 64}" width="{cell}" height="{cell}" rx="4" '
            f'fill="{trend_color(metrics["runtime_success"], metrics["runtime_known"], metrics["runtime_unknown"])}">'
            f'<title>{html.escape(run_id + " " + runtime_title)}</title></rect>',
        ])

    lines.extend([
        svg_text(12, height - 16, "green: all known pass; red: at least one failure; amber: pass with unknowns", size=10, fill="#57606a"),
        "</svg>",
    ])
    return "\n".join(lines) + "\n"


def write_history_svg(index: dict, svg_path: Path) -> None:
    svg_path.parent.mkdir(parents=True, exist_ok=True)
    svg_path.write_text(render_history_svg(index), encoding="utf-8")


def render_history_summary(index: dict) -> str:
    """Render the README history summary block from history/index.json."""
    runs = sorted(
        compatible_history_runs(index),
        key=lambda run: str(run.get("recorded_at") or ""),
        reverse=True,
    )[:HISTORY_RECENT_LIMIT]
    lines = [
        "*Auto-generated from `history/index.json`.*",
        "",
        f"![Compatibility history](history/{HISTORY_SVG_NAME})",
        "",
        "| Run | Recorded | tt-metal | Patched build | Installer | Runtime ttsim | Notable failures |",
        "|---|---|---|---:|---:|---:|---|",
    ]
    if not runs:
        lines.append("| — | — | — | — | — | — | No history yet |")
        return "\n".join(lines)

    for run in runs:
        metrics = history_run_metrics(run)
        run_id = str(run.get("run_id") or "unknown")
        run_url = str(run.get("run_url") or "")
        run_cell = f"[{run_id}]({run_url})" if run_url else run_id
        recorded = str(run.get("recorded_at") or "")[:10] or "—"
        ref = str(run.get("tt_metal_ref") or "main")
        sha = str(run.get("tt_metal_sha") or "")
        tested = f"`{ref}@{sha[:7]}`" if sha else f"`{ref}`"
        failures = metrics["failures"]
        if not failures:
            failure_cell = "—"
        else:
            shown = failures[:3]
            extra = len(failures) - len(shown)
            failure_cell = ", ".join(shown)
            if extra:
                failure_cell += f", +{extra} more"
        lines.append(
            f"| {run_cell} | {recorded} | {tested} | "
            f"{format_ratio(metrics['build_success'], metrics['build_known'], metrics['build_unknown'])} | "
            f"{format_ratio(metrics['install_success'], metrics['install_known'], metrics['install_unknown'])} | "
            f"{format_ratio(metrics['runtime_success'], metrics['runtime_known'], metrics['runtime_unknown'])} | "
            f"{failure_cell} |"
        )
    return "\n".join(lines)


def status_cell(status: str, stage: str = "") -> str:
    """Return an emoji status cell, adding a short stage hint on failures."""
    normalized = (status or "").lower()
    emoji = STATUS_EMOJI.get(normalized, "⏳")
    stage_label = FAILURE_STAGE_LABELS.get((stage or "").lower(), "")
    if emoji == "❌" and stage_label:
        return f"{emoji}({stage_label})"
    return emoji


def first_failed_stage(data: dict) -> str:
    """Infer the first failed build pipeline stage from a status.json object."""
    explicit = str(data.get("failure_stage") or "").lower()
    if explicit and explicit != "na":
        return explicit
    for key, stage in (
        ("patch_status_patched", "patch"),
        ("deps_status_patched", "deps"),
        ("build_status_patched", "build"),
        ("artifact_status", "verify"),
    ):
        if str(data.get(key) or "").lower() == "failure":
            return stage
    if str(data.get("status") or "").lower() in {"failure", "cancelled"}:
        return "workflow"
    return ""


def render(by_os: dict[str, dict]) -> str:
    sha = ""
    ref = ""
    repo = ""
    for data in by_os.values():
        val_sha = data.get("tt_metal_sha")
        if not sha and val_sha:
            sha = str(val_sha)
        val_ref = data.get("tt_metal_ref")
        if not ref and val_ref:
            ref = str(val_ref)
        val_repo = data.get("tt_metal_repo")
        if not repo and val_repo:
            repo = str(val_repo)
        if sha and ref and repo:
            break
    sha_short = sha[:7] if sha else "<sha>"
    ref = ref or "main"
    repo = repo or "tenstorrent/tt-metal"
    tested = f"`{ref}@{sha_short}`"
    if sha:
        tested = f"[{tested}](https://github.com/{repo}/commit/{sha})"
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append(HEADER_NOTE)
    lines.append("")
    lines.append(f"**Last updated:** {ts}")
    lines.append(f"**Tested tt-metal:** {tested}")
    lines.append("")
    lines.append("| Distribution | Vanilla | With patches | Runtime ttsim | Logs |")
    lines.append("|---|:-:|:-:|:-:|---|")
    known_oses = {os_id for os_id, _ in ROW_ORDER}
    for os_id in by_os:
        if os_id not in known_oses:
            print(
                f"warn: OS '{os_id}' found in artifacts but missing from ROW_ORDER",
                file=sys.stderr,
            )
    for os_id, name in ROW_ORDER:
        data = by_os.get(os_id)
        if data:
            patched_status = (data.get("status") or "").lower()
            patched_emoji = status_cell(patched_status, first_failed_stage(data))
            run_url = data.get("run_url", "")
            log_cell = f"[run]({run_url})" if run_url else "—"

            try:
                patch_count = int(data.get("patch_count") or 0)
            except (TypeError, ValueError):
                patch_count = 0
            vanilla_status = (data.get("vanilla_status") or "").lower()

            if patch_count == 0:
                # No patches needed for this distro: vanilla and patched
                # are by definition identical.  Showing the same emoji in
                # both columns with a "(no patches)" note keeps the
                # contrast visible without misrepresenting the data.
                vanilla_cell = patched_emoji
                patched_cell = f"{patched_emoji} (no patches)"
            else:
                # Patches exist.  vanilla_status comes from the pre-flight
                # pass that runs install_dependencies.sh without applying
                # them; older artifacts may not have this field, in which
                # case we leave the cell as ⏳ rather than guess.
                vanilla_cell = status_cell(
                    vanilla_status,
                    str(data.get("vanilla_failure_stage") or ""),
                )
                patches_dir = f"patches/{(data.get('distro') or '').lower()}"
                noun = "patch" if patch_count == 1 else "patches"
                patched_cell = (
                    f"{patched_emoji} ([{patch_count} {noun}]({patches_dir}/))"
                )
            runtime_status = str(data.get("runtime_status") or "na").lower()
            runtime_target = str(data.get("runtime_smoke_target") or "")
            if runtime_status == "na":
                runtime_cell = "—"
            else:
                target_suffix = " (`risc-compute`)" if "risc_compute" in runtime_target else ""
                runtime_cell = status_cell(runtime_status, "runtime") + target_suffix
        else:
            vanilla_cell = "⏳"
            patched_cell = "⏳"
            runtime_cell = "⏳"
            log_cell = "—"
        lines.append(
            f"| {name} | {vanilla_cell} | {patched_cell} | "
            f"{runtime_cell} | {log_cell} |"
        )
    return "\n".join(lines)


def render_install(by_os: dict[str, dict]) -> str:
    """Render the tt-installer verification table.

    Schema mirrors the build (deps/build) table: a Vanilla column shows
    the result of the released ``install.sh`` and a "With patches"
    column shows the result of running install.sh after applying the
    patches in ``patches/<distro>/installer/``. OSes that need no
    installer patches (``install_patch_count == 0``) synthesise the
    patched cell from the vanilla result and tag it ``(no patches)`` so
    the column is never empty.
    """
    lines: list[str] = []
    lines.append(INSTALL_HEADER_NOTE)
    lines.append("")
    lines.append("| Distribution | Vanilla | With patches | Logs |")
    lines.append("|---|:-:|:-:|---|")
    for os_id, name in ROW_ORDER:
        data = by_os.get(os_id) or {}
        # Prefer the new per-leg fields; fall back to the legacy
        # install_* keys so old artifacts (one cycle of overlap) still
        # render.
        vanilla_status = (
            data.get("install_status_vanilla")
            or data.get("install_status")
            or "na"
        ).lower()
        patched_status = (data.get("install_status_patched") or "na").lower()
        try:
            install_patch_count = int(data.get("install_patch_count") or 0)
        except (TypeError, ValueError):
            install_patch_count = 0

        if vanilla_status == "na":
            lines.append(f"| {name} | — | — | — |")
            continue

        vanilla_emoji = status_cell(vanilla_status, "install")
        installer_version = data.get("installer_version") or ""
        version_suffix = f" (`{installer_version}`)" if installer_version else ""
        vanilla_cell = f"{vanilla_emoji}{version_suffix}"

        if install_patch_count == 0:
            # No installer patches for this distro -> the patched
            # column is by definition the vanilla result.
            patched_cell = f"{vanilla_emoji} (no patches)"
        else:
            patched_emoji = status_cell(patched_status, "install")
            patches_dir = (
                data.get("install_patch_dir")
                or f"patches/{(data.get('distro') or os_id.split('-')[0]).lower()}/installer"
            )
            noun = "patch" if install_patch_count == 1 else "patches"
            patched_cell = (
                f"{patched_emoji} ([{install_patch_count} {noun}]({patches_dir}/))"
            )

        run_url = data.get("run_url", "")
        log_cell = f"[run]({run_url})" if run_url else "—"
        lines.append(f"| {name} | {vanilla_cell} | {patched_cell} | {log_cell} |")
    return "\n".join(lines)


def replace_block(readme_text: str, body: str,
                  start: str = START_MARKER,
                  end: str = END_MARKER) -> str:
    s = readme_text.find(start)
    e = readme_text.find(end)
    if s == -1 or e == -1:
        raise SystemExit(f"markers not found in README: {start}/{end}")
    if e < s:
        raise SystemExit(f"markers are out of order in README: {start}/{end}")
    head = readme_text[: s + len(start)]
    tail = readme_text[e:]
    return f"{head}\n{body}\n{tail}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--artifacts-dir", required=True, type=Path)
    ap.add_argument("--readme", default=Path("README.md"), type=Path)
    ap.add_argument("--history-dir", type=Path,
                    help="write per-run status snapshots and history index")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the README would change; do not write")
    ap.add_argument("--require-os", nargs="+", default=[],
                    help="fail if any of these target_os values is missing "
                         "from the collected status.json files")
    args = ap.parse_args()

    if not args.artifacts_dir.is_dir():
        print(
            f"error: {args.artifacts_dir} is not a directory",
            file=sys.stderr,
        )
        return 1

    by_os = collect(args.artifacts_dir)

    missing = [os_id for os_id in args.require_os if os_id not in by_os]
    if missing:
        print(
            "error: required target_os values are missing: "
            + ", ".join(missing),
            file=sys.stderr,
        )
        return 2

    recorded_at = (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )
    history_update: tuple[str, dict] | None = None
    history_index: dict | None = None
    if args.history_dir:
        history_update = updated_history_index(
            by_os, args.history_dir, recorded_at
        )
        history_index = history_update[1]

    body = render(by_os)
    install_body = render_install(by_os)
    old = args.readme.read_text(encoding="utf-8")
    new = replace_block(old, body, START_MARKER, END_MARKER)
    # The install-phase table is optional: only update it if the
    # corresponding markers are present, so the script remains
    # backward-compatible with branches/forks that do not have it
    # yet.
    if INSTALL_START_MARKER in new and INSTALL_END_MARKER in new:
        new = replace_block(new, install_body,
                            INSTALL_START_MARKER, INSTALL_END_MARKER)
    if (
        history_index
        and HISTORY_START_MARKER in new
        and HISTORY_END_MARKER in new
    ):
        history_body = render_history_summary(history_index)
        new = replace_block(new, history_body,
                            HISTORY_START_MARKER, HISTORY_END_MARKER)

    if args.check:
        if old != new:
            print("README compat table is out of date", file=sys.stderr)
            return 1
        return 0

    if old != new:
        args.readme.write_text(new, encoding="utf-8")
    if args.history_dir:
        history_index = write_history(
            by_os, args.history_dir, recorded_at, history_update
        )
        write_history_svg(history_index or {}, args.history_dir / HISTORY_SVG_NAME)
    print(f"processed {len(by_os)} OS result(s); README {'updated' if old != new else 'unchanged'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
